### ISSUE TITLE
[Server threat/CRITICAL]: [Ganja] Make sure you have your Worlds loaded!

### ISSUE THREAD

**Issue by xealah** [Wqrro/Ganja#3]
[Server threat/CRITICAL]: [Ganja] Make sure you have your Worlds loaded! - I have added an all world loader plugin however it still does not work, any solutions?

**Comment by Wqrro** [comment]
For the worlds youre using with this core, id put them in the `pocketmine.yml` file found in your server's home directory. This will load those worlds earlier. Also make sure your world name matches up and that the location properties in this core are set **after** the target world is loaded.

No need to provide any generator details if the world already exists.
![image](https://user-images.githubusercontent.com/67123872/164817194-a4508278-78fa-44a1-a449-66d6de9d18c4.png)

**Comment by xealah** [comment]
How do I make the properties set after the target world is loaded? If it's possible, could you send me a version which does' that as I'm pretty new here.

**Comment by Wqrro** [comment]
> How do I make the properties set after the target world is loaded? If it's possible, could you send me a version which does' that as I'm pretty new here.

![image](https://user-images.githubusercontent.com/67123872/164914371-e5fb4d5b-f70e-4ce6-adfe-d2b5ec797d43.png)
This is from the read-me

Then read the `Variables.php` class

**Comment by Wqrro** [comment]
@xealah everything work out?
