### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by FahZoh** [Wqrro/Ganja#5]
PocketMine-MP Crash Dump Sun Apr 24 23:58:31 UTC 2022

PocketMine-MP version: 4.3.1 [Protocol 503]
Git commit: f7dce4af8802ce28a8286e1c8002af19cf986c62
PHP version: 8.0.18
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: Ganja

Error: Call to undefined function Warro\onEnable()
File: plugins/Ganja-Ganja/src/Warro/Base
Line: 125
Type: Error
Backtrace:
#0 pmsrc/src/plugin/PluginBase(137): Warro\Base->onEnable()
#1 pmsrc/src/plugin/PluginManager(445): pocketmine\plugin\PluginBase->onEnableStateChange(true)
#2 pmsrc/src/Server(1386): pocketmine\plugin\PluginManager->enablePlugin(object Warro\Base#25021)
#3 pmsrc/src/Server(1012): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#24899)
#4 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#5 pmsrc/src/PocketMine(327): pocketmine\server()
#6 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

Code:
[116] 		foreach ($this->getServer()->getWorldManager()->getWorlds() as $world) {
[117] 			$world->setAutoSave(false);
[118] 			$world->setTime(World::TIME_DAY);
[119] 			$world->stopTime();
[120] 			foreach ($world->getEntities() as $entity) {
[121] 				$entity->flagForDespawn();
[122] 			}
[123] 
[124] 			if ($world->getFolderName() === Variables::SPAWN) {
[125] 				onEnable($this->utils->spawnLocation = new Location(0.5, 101, 0.5, $world, 0, 180));
[126] 			} else {
[127] 				OnEnable($this->utils->nodebuffLocation = new Location(100.5, 50, 100.5, $world, 0, 0));
[128] 			}
[129] 		}
[130] 
[131] 		if (is_null($this->utils->spawnLocation) or is_null($this->utils->nodebuffLocation)) {
[132] 			$this->getLogger()->critical('Make sure you have your Worlds loaded!');
[133] 			$this->getServer()->shutdown();
[134] 		}
[135] 

Loaded plugins:
DEVirion 1.2.8 by poggit, SOFe for API(s) 4.0.0
DevTools 1.15.0 by PocketMine Team for API(s) 4.0.0
Ganja 1 by Warro for API(s) 4.0.0

uname -a: Linux eb0f8a40-9477-4323-9b4d-20613f83041f 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64
Zend version: 4.0.18
Composer libraries: 
- adhocore/json-comment 1.1.2@fc2f76979f0a44a5f5bc2a2b600d0762fe0e78e7
- brick/math 0.9.3@ca57d18f028f84f777b2168cd1911b0dee2343ae
- daverandom/callback-validator unknown@unknown
- fgrosse/phpasn1 v2.4.0@eef488991d53e58e60c9554b09b1201ca5ba9296
- netresearch/jsonmapper v4.0.0@8bbc021a8edb2e4a7ea2f8ad4fa9ec9dce2fcb8d
- pocketmine/bedrock-data 1.7.0+bedrock-1.18.30@c8f323ff0cbdb36a5d95e7e4a23969f562445be0
- pocketmine/bedrock-protocol 9.0.1+bedrock-1.18.30@9d3cc87c4d26c002dd42aa9af20c0cd47a72018e
- pocketmine/binaryutils 0.2.4@5ac7eea91afbad8dc498f5ce34ce6297d5e6ea9a
- pocketmine/callback-validator 1.0.3@64787469766bcaa7e5885242e85c23c25e8c55a2
- pocketmine/classloader 0.2.0@49ea303993efdfb39cd302e2156d50aa78209e78
- pocketmine/color 0.2.0@09be6ea6d76f2e33d6813c39d29c22c46c17e1d2
- pocketmine/errorhandler 0.6.0@dae214a04348b911e8219ebf125ff1c5589cc878
- pocketmine/locale-data 2.5.0@df6fc7f2b48850b306c60466a11f7a27bb8fe1de
- pocketmine/log 0.4.0@e6c912c0f9055c81d23108ec2d179b96f404c043
- pocketmine/log-pthreads 0.4.0@61f709e8cf36bcc24e4efe02acded680a1ce23cd
- pocketmine/math 0.4.2@aacc3759a508a69dfa5bc4dfa770ab733c5c94bf
- pocketmine/nbt 0.3.2@3e0d9ef6b6c5fb45e3745a121296e75631b3eefe
- pocketmine/pocketmine-mp 4.3.1@f7dce4af8802ce28a8286e1c8002af19cf986c62
- pocketmine/raklib 0.14.4@1ea8e3b95a1b6bf785dc27d76578657be4185f42
- pocketmine/raklib-ipc 0.1.1@922a6444b0c6c7daaa5aa5a832107e1ec4738aed
- pocketmine/snooze 0.3.1@0ac8fc2a781c419a1f64ebca4d5835028f59e29b
- ramsey/collection 1.2.2@cccc74ee5e328031b15640b51056ee8d3bb66c0a
- ramsey/uuid 4.3.1@8505afd4fea63b81a85d3b7b53ac3cb8dc347c28
- rhumsaa/uuid unknown@unknown
- symfony/polyfill-ctype v1.25.0@30885182c981ab175d4d034db0f6f469898070ab
- symfony/polyfill-php81 v1.25.0@5de4ba2d41b15f9bd0e19b2ab9674135813ec98f
- webmozart/assert 1.10.0@6964c76c7804814a842473e0c8fd15bab0f18e25
- webmozart/path-util 2.3.0@d939f7edc24c9a1bb9c0dee5cb05d8e859490725

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtOWtv3MiRf4UZB4h0J476xdcEY8ix7OAAey2stNncZRZCvzjDFYfksklJ48X+96tukkNyLDvJ
IZ8O8ZNdXV3vqq5q/bpIy3rPm/tHXZusLBYrdrFosr1erHAYoJixCOMlDVCEYKOtui20JEEYEJww
RCimhBLYzLlp3tV1WS9Wvy6aQwV4i259sdhrY/jWQt7yPPea0msLpdOs0MpL20I2wNr7kQP2ZlMW
7woucn12DgfTNs/fZ7k9ebkr9/pSlkXD4Vx9WeXtNivM5Z958TP33b+XppaXjszln7jRy2pXWRrd
+b+PD7g5kAbVSQBWqLmE778tXiGv2ltM+7ejcnnj/rOHzjCNzleD8Bbiv56p8Ap/7fhHXoBR6jPG
AqBQlfJBN3sQYLPp0Dabkc1I9LbhjX6748VWnzV1qx0PMuFxq2vwJsgVh98k27P3X2tHtwOeleJn
LZupPq9IgAh2bOgLbBAmJ2y6nTldMxD+ujydep9qpetXhMVJ4liyCcsbd/YjnD2jiH2F6/09xIgB
y8hm4Gm1eAvxaT6U3FG/8F6Qpm2y3Gw2HyG8PpRbsMwreuEBoazY/g2HP3mnAXjcJOzLzSHanA7B
V3Qg0YkOprOpOxR2h84wBqRa/9JmtT7rOYboJ6/a8Xp1eXnKeKTvf7xZWqQTtjYrzhc//Xax0P/y
bP2/ZBoI0h24z4rHMn/Ue100QEWBvrJZDLsAcZQAIEulrdgYhwDdNJsGipjmcued/b7ZZcZ/vdVN
H57nbvFjWedqSLcJyJyde9x4v3+yi3PvVyCOcdQT3TQd3H9tdPOmbcpb/qjPUp4bff5Hhxm/hHkH
JfLMUV+t7v7r47v76zf/3eMnX+I3ZeUOdBgEHTFGlXpUkPld0WRNpgeptV0eerEJPh4F8t2W/zrN
+fZ9WV9rU/GnYuBCjqi/uTWFtftgx40snXF+X+aQON9xK6m3Xq+9v/A6s343q9XtzZsfvxukCCZS
HGOj94pLMNDZivKhlNzF0dor9JM3LM/QMrjwoKZceO6rEwEWAIzReS9/OMrvaXBHzzua8P70Mu8C
Qke0afo19hg5toHlh04lOPKPT+w3+NWtKOqtSQePWFtm5r6Au+xbpjj3ytp7Ge9U7PPe3HT05Bj5
XfGyYS5rCBfJ87M/fOQP2jNtrb1D2Xo7CGT7UXtdFni5rYvqd3/o9KP0BapjPpld26jyGE2UzbS3
AbD47d/X57+vz//X1+dwLRl7EV2/+0tWu+7510XBbYc8gi4Wx9Z6gZdkGQOEt82urI3NjgpMldlb
7vbTe23J8iqzcLZES2TXXRSoxcoG68VC6UoXyh6FPVOmzfUUsOfuouyIbjaPToTNRunhayKWzXnA
vb178/3dDzcAeNLCZI3u8/daP96VZW6mOg2guU44AElnSo3W8u403/+r1Br4gxqjJN9QY9c0lQEf
gy12rVjKcj/x4+WRBijbdRajpkOnMVFzrqHL739KrzEivqHhpGyMqt18ur378dP3H65PfGQbJ16D
wI3uhFq+EL1wxveL0n/KPvNauZXKjJXR54XJnMjPjS6sms7Xb6HvAPIxKIRtrCrezNZ5Jp73+RRS
gh7GzECVnBMxv+QgNZ2CPgOh6VpIGEN3UwhcXGAgUGEK27XFg6s09uZDS7q0jpH1oWrKHkAsoO9o
x3NtPRNQlXtYEoQottd317pmRVpOkQAGpp1Bmmq63KrZaj/b3HEzU8c03GozO/KzccE1Glc/6lyJ
XhPUmRta77xzAmA54F50hWx6dF/WjSNmkawN9gewemHZ9V/eEff25sPcW0Uzs447kE0hN9efZidU
ee+QToGdo2cnd3MPVqXJnmd2cTFrZjjNDppfmxt9Yl0sYBZoXS5u286Ggy2+B+toN5LMiO725cwb
t9m+yvVfP84Uz7YiK3h9ABjEzTICUFM+6CL7PHf7ScDD0or3Bc4TtFsnwOc+Cqy0NlIP3JEiwM36
6HNWdSU0WQaw/B+Id+/TjYS+f2JDm+e7qg9OG2caLiqeT8rVLO1tLkH9GF90wIZdmog2y8F0BIUJ
6G7u4VpYrNw8AxzqsillCVQDRIFHZkewNFJSM57GMSJSk5jHJA41ljFChKc4kWkShzK0mrS9KB+y
on32tEBpzBnyExZFPqOE+olgygfWmKYxdB849YIlBt/6mPp8r0LmQad3+/HGu9Yi40W3i1HoY++M
IEJ8RH0cnXvPcXgfsoWzyayeaBfr7BhDu+q+NINEtkzZRd4v4C6AQNT1PeRXDaOMdrWPqx3YoNaX
Ni99wOlHUWxT6iqVJI3CJEpSxBnjQRoISTgRIUIKRSFJNdJRrG0UiTqTD5d9QUPLZEmvJA8iheMU
kTiNWRpFkSA4jKXCCcYCKa0JZZRrV3LBd1As4L6CGpgLLh/8R55nUIrtvA62fiig/77q/7d1aVuX
xuhLUJqbws4dj2QJprjSOmUx9IJYBVQHsQ6RTIKACZQIGDYxCCV4QpIQaBS6qbXRvJY7p/+eV5WL
5keXg1exEBIaWR5rJQhERaQ5AScrlvJEywQihaRSxMrl+NCTXQqtalj5IDt3loyW6D8HINg1XlJ0
JeMUQiRNkRRK0JAHKgl0BDwITcIkDUICPb7Q6GXSY+guEuv9L8gnikoZR5IpEkoIXaUY4TzhKUES
ScUiHoEtYn1C3pUGd9c4J4JBrwIuI615gnkquIqVZEmcBlJTJnVIkkgFOoRtPqf0ohOhekFUhCyK
IwZBFYZCcrBpEMcBYUTHgSRUkkDHMgg4OSFom3E3s9W9aOiKJZpTRJOE6lSlgiZSUUQ0wUGoAgSk
Y4ISiM8TSmVejjQgKqz8oYrClGhKVRhjKmmiSCIJkSyUONJYnUjjnpFgoFJ5L04IpBQH1owjRlks
IMJ1THCiRYpJkKYYdIoT65MTcfLSXvpDsJBlYCmlYSqjlAgI5AAJiqDiIBaGHOM04iQSIk5BKH1K
aetkcUkQygQTidIEBYGMQQGKUawlUThKRBKmDDEJkn5BwZ9cRB2pEHiCGWOZUnCYJEwzDXlPuIT5
OYwRx5AGVJ4kwbEQMCgjnEtJoyDhAYp5mKgUchBCM+VRhLiIKJWBTJhI5yQK0Qz9zRXVSCU6DUUo
g1SwQNOIBRwT6GRCHQUhxYJC4p9YZPz0XaPiboWrf6LET2jV/KFr3yDdGOQF1lAWqEhAChGKNIoD
JUkEYRREMfwVmuE4SNmLVPysksMNeZUQwkPGoEDJUEaKcx7YPzElGEHoackiGnN9Yl9TlOVnPTSE
V4hDQYHSHMVYMpxwnIZMQ3oxFcQ0sAU4SDRJhG0r+N7og02DsYmwUxq5kvArYlqDdUkMbaKARGJI
BBgFodaxokKEUE34SKRtM3W0K4RqwFMojpBOVMRQNgM4EomAckltmZSURZLY+K937d5wPpz/srqb
wz4tiwN4MD9AT5r7Q3v7CKLaFKEIUgPHRCbASOAoUEwhyhTcwhDcYRInMbLB9RItuDJiPKEVKM0E
J4pZjdNEKKRxIgiHPIkYpgFUBKj2cdoNI/sSxormEsqRrvub0t4VYRIyGYEHY8RiKAMxI+A4jcAv
CsOVA4JBvSXBjEgFWeLbeutSn9rUT2iSRhpiiUlwoxCJtBdlIAUKVAw1MmEJioCMm4WO8bA8uCYL
ii30QWbl2Qe1TcEL0HtftsaHTrzJTJNJs9oUntePbCvPtUIWsitNs/IsmllOyMINCWTapvRrXUG7
PT9tB77xsKyh8VtW+321zEoLNtCf+PblesR0oL61m3B3YKObBjp8M2K3RvvdRNuDnCRtZQe0+lui
dChTWaC56YDumOc98dq2O4Up84l4VQ01pK41iA3VvdC5MwlwcEK22602zbB1FMoNaH7Xotp8chyq
smpzt/R/aXWrfQMd9sqjZMC3KoO2HbKuffDNw8pjjpF9IvVrrrLWOFB3wmIMJwRcGw/GtwdNK7r9
kQq1KMPM61CPh/vImPFEdm2/jzyBwGCbbq8BQh12p7N9m+0kcfPbysObwn2NXnQy6JS3eeN3P3Fd
ef2wtyn2Goa3g8Ph5lBI/6msH0AimJyUn2f7DJBJENp9GAycZOA6jzhR7dMVNLU2rmEmtO9uowe/
3OuPUnd0y2vBt9ofq18fDz3An0ozUgU1yye/E/pLns6YWQlRSKEx7vjkpeD5oIkD2feOmX4YEXbc
mGM++86lZhDO+XcSEBY4qNdt9vKPQvXCqnZf9VTs51f0637q4YawgecQPj15u/WP2QNKhiU/8a2d
PKDPtqPZJOcFb+TOt92G2ZW5Gv09Yvt9cIVjqvu6cE8fjtZRVzDYvmn7HMOs80FbFZWNPEh1l2kD
6yrnh758GBg7/G7tOrCRJIwjWXrwn+GCGoD962cf9VsuD+6Mr7L6SHsW/VNbg99s8ZooAqOo78ZT
MzFKvwf9PdxUU6E9DzSR2s+5fQ7Y6slGh6z7Cj26o0sWqD7go0H2sRD3P9Hw+598rrzuNdyTOQyJ
alPYbHcFplMFZLfGAl+4CG8gXAc1u5LbQ8aa62LqeBXZe9gxWIK4QLVx8+fi1c1x5b0tizTbelaX
TfHqljfem6r2CPUwXeFkhZj3w91bzw7GUD/KRq1nbwC9/NYF7lXf2mJNEMKQLk+7rAHTwQW4LtPU
3otF2Rby6HoI7kx3P4U167IAGq4C2ymrKxJrDCFoo6w7YNbWtjDiQBKkebbd9XS7Y7zI9uCbCaF9
KbrlltucUXoNxzt/HiGOgC0PdhrvVtVj5U6pLE0zCXX0sIYy2180ZX0steuh9toHibWz+1iNtTpu
2xZqff3u/ZsfPtxtij7UXHysu7DoQTUU0U4C+7WE+doAUbX+D/erv4VtNDjpHjP9ZB9YGw4WXceb
4lmUz759OO4s0Lkjq9Zo6X5vCsdyOXXQxGeP4RonmNKjNFkFIEtpCP21LrYQUL/9L6Y6iXI=
===END CRASH DUMP===

**Comment by Wqrro** [comment]
if you dont know PHP, dont change the code that was presented to you.

remove the `onEnable()` you added inside of `onEnable()` for whatever reason
![image](https://user-images.githubusercontent.com/67123872/165090562-7d1dbf5b-9890-4b9f-95f9-dded5c8dfa65.png)

**Comment by cqdetdev** [comment]
broski 💀
