### ISSUE TITLE
Ranks

### ISSUE THREAD

**Issue by FahZoh** [Wqrro/Ganja#6]
Hi 
what is the command to create a rank and how have the colors and permissions been configured?

**Comment by Wqrro** [comment]
> Hi 
> 
> what is the command to create a rank and how have the colors and permissions been configured? 

Everything is hardcoded, so to add a Rank you'll need to deal with PHP. Read carefully, every step needed to successfully add a Rank is listed below.

1. Add your Rank to `RankManager.php`
2. Configure your Rank format, head over to `Utils.php` where you can set the NameTag & Chat format. Look for `getTagFormat()` & `getChatFormat()`
3. Congratulations you're done
